### ISSUE TITLE
Redirect debug print to "Output Log"

### ISSUE THREAD

**Issue by peterpeterparker** [dfinity/motoko-playground#61]
### Feature Description

It may be a mistake  on my side but, it seems that debug outputs are not redirected to the "Output Log" pane. I think it would would be quite handy.

### Sample

```
import Debug "mo:base/Debug";

actor HelloWorld {

  public func print() {
    Debug.print("Hello World!");
  };
  
};
```

### Screenshot

<img width="1513" alt="Capture d’écran 2021-07-22 à 09 30 40" src="https://user-images.githubusercontent.com/16886711/126603821-4dbe81f0-14e6-4615-859f-fbc9788f6ae9.png">

**Comment by chenyan-dfinity** [comment]
That's an expected behavior. `Debug.print` only prints to the replica log (you can only see it in the `dfx start` terminal when you run locally). It's never visible on the IC. 

To see the result on Candid UI, you can return the text, e.g.,
```
public func print() : async Text {
  "Hello world!"
};
```

**Comment by peterpeterparker** [comment]
Yeah, that's why I provided it as a "Feature request" or "idea" if you rather like. I think from a user perspective of the playground it would be helpful to get these logs in the playground too.

**Comment by chenyan-dfinity** [comment]
Okay. I can see two ways to solve this problem. Let me know which is closer to your feature request.

1) We can add an interpreter or WASI mode in the playground. In there, we can easily output Debug.print into the UI. The limitation is that you cannot deploy this to the IC. #49 is the tracking issue.
2) Before you deploy the Wasm to IC, we replace `Debug.print` to an inter-canister call to the playground frontend, so that it can print the result.

**Comment by peterpeterparker** [comment]
Thanks for the suggestions. 

2. is probably the closest to what I have in mind but, just my two cents.
